### ISSUE TITLE
Investigate and mitigate bug where images not producing output in CRAFT

### ISSUE THREAD

**Issue by eamonniknafs** [BU-Spark/ml-herbarium#42]

**Comment by eamonniknafs** [comment]
Here is a relevant error output:

```
(.env) [en@scc-q32 CRAFT-pytorch-master]$ ./bash_submit.sh 
Loading weights from checkpoint (craft_mlt_25k.pth)
Traceback (most recent call last):rkgrp/ml-herbarium-grp/ml-herbarium-data/scraped-data/20220425-160006/438835964.jpgg
  File "test.py", line 164, in <module>
    image = imgproc.loadImage(image_path)
  File "/usr4/ugrad/en/ml-herbarium/CRAFT/CRAFT-pytorch-master/imgproc.py", line 12, in loadImage
    img = io.imread(img_file)           # RGB order
  File "/share/pkg.7/python3/3.8.10/install/lib/python3.8/site-packages/skimage/io/_io.py", line 48, in imread
    img = call_plugin('imread', fname, plugin=plugin, **plugin_args)
  File "/share/pkg.7/python3/3.8.10/install/lib/python3.8/site-packages/skimage/io/manage_plugins.py", line 207, in call_plugin
    return func(*args, **kwargs)
  File "/share/pkg.7/python3/3.8.10/install/lib/python3.8/site-packages/skimage/io/_plugins/imageio_plugin.py", line 10, in imread
    return np.asarray(imageio_imread(*args, **kwargs))
  File "/share/pkg.7/python3/3.8.10/install/lib/python3.8/site-packages/imageio/core/functions.py", line 265, in imread
    reader = read(uri, format, "i", **kwargs)
  File "/share/pkg.7/python3/3.8.10/install/lib/python3.8/site-packages/imageio/core/functions.py", line 181, in get_reader
    raise ValueError(
ValueError: Could not find a format to read the specified file in single-image mode
```

**Comment by eamonniknafs** [comment]
Fixed CRAFT so that it skips over corrupted or otherwise unusable images
